name: Deploy
on:
  push:
    branches:
      - '*'
jobs:
  deploy-master:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: self-hosted
    environment:
      name: 'main'
    steps:
      - name: instalar git
        run: sudo yum install git -y
        
      - name: Eliminar antes de clonar
        run : rm -rf ${{secrets.PATH}} 
        
      - name: Crear carpeta con día y hora    
        run: mkdir ${{secrets.PATH}} 
        
      - name: Ir a carpeta con día y hora
        run: cd ${{secrets.PATH}}

      - name: permisos en otra ruta
        run: chmod 777 ${{secrets.PATH}}
      
      - name: Clonar Repositorio
        run: cd ${{secrets.PATH}} && git clone https://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@github.com/Samuelcloud07/java-tomcat-maven-example.git
      - name: instalar java
        run: pwd
      - name: inicie java service
 
        run: mvn --version
      - name: change directori del projecto 
        run: cd  ${{secrets.PATH}} && sleep 20
      - name: build mvn

        run: mvn clean install    
      - name: Pasar el war        
        run : |
                  cd /home/ec2-user/actions-runner/_work/project-java/project-java/project-java/target
                  cp java-tomcat-maven-example.war /usr/local/tomcat/webapps/
              
